sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/gradle
  - secure: D7K+oSjSve9jLo+UO1X/k6YCCQC6iy9mx0eWwMyuaZd5n7EZp5Rx/Wz4u6Bd3bLa74WqLd+1aw/z1/u6BOE9AZY1oBMJundaNfAYXZjfe/pfBZhME9CVYKpI60xuUe6f6RcT6Ek8lkxoDFTlDxW5e502NZgNbYzRFUWtioFYhGIRdYzpBGtHZ5MMyy24VSnN7muRq2A+iPiOVUOhHzdUCKz1ndLIF0RCdctMrluLTE8E3BcN1SFADGa/VV/Zoqtb6ZwWAc/R7bI4c7Qk8z7CGEwaW4uvNactVgI+GFUEzjs3iOpzyScKoR9l1j4gdkaaiXCi1AjHOv442vME8qw7qjHTWqm8FYdZ2B/np41+WeiL2CVodd/SwoA8Kz36gTeiDexQThMLI5+x5yN7jitJ7ja0uSRDoKxD/nAlpXDYQ0ui1VrCevC/Y2kAl6wPGOkQy8a8bAavTWifkL1lq8kWS5uIcCgWZM9LRQrbJKq2t9gYgNHNbgrQfIKSXbJLWyJNgeCKRBmgsX3Uo6fwa4ot30Qdi3so4rJmMrkNQasL02ivt+33gZ7Cgo22w7Nj6FAo05sxj2+Rep/K2NqO5YMThIT61j/ZKainNn9Ig9pt1rEhI+NY4Fr0X+025spRiTqSKPBvWiG/od60JT3UtpcfhwoWppRZIKKitPitOjPkcUg= # DOCKER_USERNAME
  - secure: fV47hc1WnHVKrA5V/UwzGvMOWwwSLaOdoTCQW/lFJSe9wAdOyMneRRnJuCFjxcs7ktnjMKJ9DWeASetBrjm/GzM2fdAqaWO+EelRbpVqSxG4tAmsteoOkuK9048gwBPM9c6ySnJA54HbrmcKI7vOtk7RSQ4Vnc8fzSl2BcjzncLgqyphq7cWACHiYS+2rxnnF0y5W4R5OW2LZ8lyHH0x7UhMJ8YHxAATmAsuFpjebSOhfp/I4oJ2u8wkV7ULkIkTsNSSMUCuFbYluo5+k1fw21SirTxVSY/wBg64IgWUfKbVPQJ2ueJ5OOvaaiXhaBlRYE+H39nFhR4/x0wdzlJoh3if4f8ynzPIWsPNqkUIPiXtS1oyPqCg3vuF14hDUGQBh+3fMg4QSBqEiU+onMz3cHZcGDi7OUzSB5FZypXdnjvIs2+IzLyBO8D7vPocWSUl595MU3uSDf7h4hE/1rjdOpw6cZM3aCBwoPrmm5uATTMUnPU+FmM8KbZbBveX8yioTSL83rd7fRY3fkEWhPxpZb7t1CuECZwltRSVivT1M2/RbDu2ULPzGk9o8PGrjcRuYLtRmh++8EcsmxxlFYM/CJAwezSrg22cHRIc6VOcgXdNBJ1FGBOHDYneEMfRYhWBoFKcOcxssSaiKFVMhxQhl6/WDa16fMJBr5SwLQBVGTg= # DOCKER_PASSWORD
before_script:
- cd jdk8
- version="$(awk -F= '/GRADLE_VERSION=/ {print $2}' Dockerfile | cut -d " " -f 1)"
- base_version="$(awk -F '[:]' '/FROM/ {print $2}' Dockerfile)"
script:
- docker build -t "$IMAGE_NAME" .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}-${base_version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}" && docker push "${IMAGE_NAME}:${version}-${base_version}"
  on:
    branch: master
