name: Build Gradle base on JDK 11

on:
  push:
    branches:
      - master
    paths:
      # '*' matches any character except '/'
      - 'jdk11/*'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      env:
        DOCKER_HUB_USERNAME: ${{ secrets. DOCKER_HUB_USERNAME }} 
        DOCKER_HUB_PASSWORD: ${{ secrets. DOCKER_HUB_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      run: |
        echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
        echo $GITHUB_TOKEN | docker login ghcr.io --username $GITHUB_ACTOR --password-stdin

    - name: Build & Push Docker Image
      run: |  
        cd jdk11
        IMAGE_NAME=ringcentral/gradle
        GH_DOCKER_PKG_IMAGE_NAME=ghcr.io/ringcentral-docker/gradle/gradle

        VERSION="$(awk -F= '/GRADLE_VERSION=/ {print $2}' Dockerfile | cut -d " " -f 1)"
        JAVA_VERSION="jdk$(awk -F '[:-]' '/FROM/ {print $2}' Dockerfile)"
        BASE_VERSION="jdk$(awk -F '[:]' '/FROM/ {print $2}' Dockerfile)"

        docker build --tag ${IMAGE_NAME} --file Dockerfile .
        
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${VERSION}-${JAVA_VERSION}"
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${VERSION}-${BASE_VERSION}"
        
        docker push "${IMAGE_NAME}:${VERSION}-${BASE_VERSION}"
        docker push "${IMAGE_NAME}:${VERSION}-${JAVA_VERSION}"

        docker tag "${IMAGE_NAME}" "${GH_DOCKER_PKG_IMAGE_NAME}:${VERSION}-${JAVA_VERSION}"
        docker tag "${IMAGE_NAME}" "${GH_DOCKER_PKG_IMAGE_NAME}:${VERSION}-${BASE_VERSION}"
        
        docker push "${GH_DOCKER_PKG_IMAGE_NAME}:${VERSION}-${BASE_VERSION}"
        docker push "${GH_DOCKER_PKG_IMAGE_NAME}:${VERSION}-${JAVA_VERSION}"